// <auto-generated />
using Jobus.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Jobus.DataAccess.Migrations
{
    [DbContext(typeof(JobusDbContext))]
    [Migration("20180513135652_WsClient")]
    partial class WsClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jobus")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Jobus.Domain.WsClients.WsClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("AddDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("add_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Ghost")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ghost")
                        .HasDefaultValue(false);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("client_name")
                        .HasMaxLength(32);

                    b.HasKey("Id")
                        .HasName("pk_ws_clients");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasName("ws_clients_hash_unique");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("ws_clients_name_unique");

                    b.ToTable("ws_clients");

                    b.HasAnnotation("Npgsql:Comment", "Table with api clients");
                });
#pragma warning restore 612, 618
        }
    }
}
