// <auto-generated />
using Jobus.Core.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Jobus.Core.Migrations
{
    [DbContext(typeof(JobusDbContext))]
    partial class JobusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Jobus.Domain.WsClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("AddDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("add_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Ghost")
                        .HasColumnName("ghost");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(32);

                    b.HasKey("Id")
                        .HasName("pk_ws_clients");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasName("ix_ws_clients_hash");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("ix_ws_clients_name");

                    b.ToTable("ws_clients");

                    b.HasAnnotation("Npgsql:Comment", "Table with api clients");
                });
#pragma warning restore 612, 618
        }
    }
}
